# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MergeSelectedFeatures
                                 A QGIS plugin
 Merge selected features in a polygon vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-01-08
        copyright            : (C) 2022 by Antonio Sobral Almeida
        email                : sobral.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2022-01-08'
__copyright__ = '(C) 2022 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MergeSelectedFeatures class from file MergeSelectedFeatures.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .merge_selected_features import MergeSelectedFeaturesPlugin
    return MergeSelectedFeaturesPlugin()
